### ISSUE TITLE
Does Math Operator work?

### ISSUE THREAD

**Issue by patelgr** [vincentrussell/sql-to-mongo-db-query-converter#64]
"select 1+2 from my_table"

Exception in thread "main" com.github.vincentrussell.query.mongodb.sql.converter.ParseException: Unsupported project expression
	at com.github.vincentrussell.query.mongodb.sql.converter.QueryConverter.getMongoQueryInternal(QueryConverter.java:241)
	at com.github.vincentrussell.query.mongodb.sql.converter.QueryConverter.<init>(QueryConverter.java:121)
	at com.github.vincentrussell.query.mongodb.sql.converter.QueryConverter.<init>(QueryConverter.java:76)
	at com.github.vincentrussell.query.mongodb.sql.converter.QueryConverter$Builder.build(QueryConverter.java:1099)

**Comment by vincentrussell** [comment]
no... not supported.  Can you even do this with mongo?
